services:
  ts-frontend-sidecar:
    image: tailscale/tailscale:latest
    container_name: ts-frontend-sidecar
    hostname: tsfrontendsidecar
    build:
      context: autocompletedev
      dockerfile: Dockerfile-ts
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY_CONFIG}
      TS_STATE_DIR: "/var/lib/tailscale"
      # tailscale serve --bg --https 443 80
      #TS_SOCKET: ${TS_SOCKET}
      #TS_USERSPACE: "false"
    secrets:
      - ts-authkey-secret
    volumes:
      - ${PWD}/ts-authkey-test/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  # tqfrontend:
  #   build:
  #     context: app
  #     target: development
  #   ports:
  #     - 8085:5173
  #   volumes:
  #     - ./app:/project
  #     - /project/node_modules
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./app
  #         target: /project
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: package.json
  autocompletedev:
    build:
      context: autocompletedev
      target: development
    volumes:
      - ./autocompletedev:/project
      - /project/node_modules
    network_mode: service:ts-frontend-sidecar
    depends_on:
      - ts-frontend-sidecar
    develop:
      watch:
        - action: sync
          path: ./autocompletedev
          target: /project
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
secrets:
  ts-authkey-secret:
    file: ~/.config/tailscale/ts-authkey-sidecars