"""Add pattern field to current train

Revision ID: 79f9089039df
Revises: 6def7d3064d9
Create Date: 2025-02-18 17:44:55.214148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79f9089039df'
down_revision: Union[str, None] = '6def7d3064d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('current_train_state', sa.Column('current_pattern', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_train_state', 'current_pattern')

