server:
  port: 7001
osm: /data/Chicago.osm.pbf
timetable:
  first_day: 2025-01-01             # first day of timetable to load, format: "YYYY-MM-DD" (special value "TODAY")
  num_days: 60                      # number of days to load, default is 365 days
  railviz: true                     # enable viewing vehicles in real-time on the map, requires some extra lookup data structures
  with_shapes: true                 # extract and serve shapes (if disabled, direct lines are used)
  ignore_errors: false              # ignore errors when a dataset could not be loaded
  adjust_footpaths: true            # if footpaths are too fast, they are adjusted if set to true
  merge_dupes_intra_src: false      # duplicates within the same datasets will be merged
  merge_dupes_inter_src: false      # duplicates withing different datasets will be merged
  link_stop_distance: 100           # stops will be linked by footpaths if they're less than X meters (default=100m) apart
  update_interval: 60               # real-time updates are polled every `update_interval` seconds
  http_timeout: 10                  # timeout for the HTTP server to respond with a package
  incremental_rt_update: false      # false = real-time updates are applied to a clean slate, true = no data will be dropped
  max_footpath_length: 15           # maximum footpath length when transitively connecting stops or for routing footpaths if `osr_footpath` is set to true
  datasets:
    chicago:
      path: /data/google_transit.zip
#tiles:
#  profile: tiles-profiles/full.lua
street_routing: true
geocoding: true
osr_footpath: true
