# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  bundleserver:
    build:
      context: ..
      dockerfile: bundler/Dockerfile
    restart: always
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "transitbundler"
    ports:
      - 8009:8000
    volumes:
      - ~/.aws/credentials:/home/appuser/.aws/credentials:ro
      - ~/.aws/config:/home/appuser/.aws/config:ro
      - transit-working:/transitworking
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 900M
    develop:
      watch:
        - action: rebuild
          path: .
volumes:
 transit-working:
